# show_downloads: false
plugins_dir: jekyll-remote-theme
plugins:
- jekyll-remote-theme
remote_theme: pages-themes/modernist@v0.2.0
github: [metadata]
title: Ed Grzetich, technical writer
description: Portfolio for Ed Grzetich
show_downloads: false
