# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|grzetich| "https://github.com/#{repo_name}" }

# gem "rails"

gem "jekyll", "~> 4.2"

gem "http_parser", "~> 0.1.3"

gem "em-websocket", "~> 0.5.3"
