# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|grzetich| "https://github.com/#portfolio" }

gem 'jekyll'
gem 'jekyll-sitemap'
# If you use any other plugins, list them here too.

# gem "rails"

# gem "github-pages", group: :jekyll_plugins

# gem "jekyll-github-metadata", "~> 2.16"

